version: '3'

services:
  library:
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon --exec npm run build
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
     - .:/home/app/library
     - /home/app/library/node_modules
  laravel-app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx
    networks:
      - app-network

  mysql-app:
    image: mysql
    command: --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: pharmaceuticalcontroller
      MYSQL_ROOT_PASSWORD: laravel
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

